services:
  - type: web
    name: library-service
    env: docker
    dockerfilePath: Library/Dockerfile
    buildCommand: docker build -t library-service -f Library/Dockerfile .
    startCommand: docker run -p $PORT:8083 library-service
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mysql
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: vtat2011
      - key: SERVER_PORT
        value: 8083

databases:
  - name: mysql
    ipAllowList: []
    plan: free

